[package]
name = "burnt-sushi"
version = "0.1.0"
description = "Spotify AdBlocker for Windows"
readme = "../README.md"
repository = "https://github.com/OpenByteDev/burnt-sushi"
license = "MIT"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2021"
keywords = ["spotify", "adblocker", "windows", "blocker"]

[dependencies]
dll-syringe = { version = "0.11", features = ["into-x86-from-x64", "rpc"], default-features = false }
capnp = { version = "0.14", default-features = false }
capnp-rpc = { version = "0.14", default-features = false }
toml = { version = "0.5", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
futures = { version = "0.3", default-features = false }
tokio = { version = "1.19", features = ["net", "rt", "macros", "fs"], default-features = false }
tokio-util = { version = "0.7", features = ["compat"], default-features = false }
winapi = { version = "0.3", features = ["winuser", "tlhelp32"], default-features = false }
wineventhook = { version = "0.2", default-features = false }
project-uninit = { version = "0.1", default-features = false }
fallible-iterator = { version = "0.2", default-features = false }
async-thread = { version = "0.1", default-features = false }
log = { version = "0.4", default-features = false }
shared = { path = "../shared", default-features = false }
native-windows-gui = { version = "1.0", default-features = false, features = ["tray-notification", "message-window", "menu", "cursor", "image-decoder", "embed-resource"] }
native-windows-derive = { version = "1.0", default-features = false }
pipedconsole = { version = "0.3", default-features = false }
widestring = { version = "0.5", default-features = false }
ctrlc = { version = "3.2", default-features = false }
clap = { version = "3.1", default-features = false, features = ["std", "derive"] }

[build-dependencies]
cargo-emit = "0.2"
embed-resource = "1.7"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
opt-level = 3

[[bin]]
name = "BurntSushi"
path = "src/main.rs"
