[package]
name = "burnt-sushi-blocker"
version = "0.1.0"
description = "Spotify AdBlocker for Windows"
readme = "../README.md"
repository = "https://github.com/OpenByteDev/burnt-sushi"
license = "MIT"
authors = ["OpenByte <development.openbyte@gmail.com>"]
edition = "2021"
keywords = ["spotify", "adblocker", "windows", "blocker", "payload"]

[dependencies]
dll-syringe = { version = "0.11", features = ["payload-utils"], default-features = true }
capnp = { version = "0.14", default-features = false }
capnp-rpc = { version = "0.14", default-features = false }
futures = { version = "0.3", default-features = false }
tokio = { version = "1.19", features = ["net", "rt", "macros", "sync"], default-features = false }
tokio-util = { version = "0.7", features = ["compat"], default-features = false }
winapi = { version = "0.3", features = ["ws2tcpip", "rpc"], default-features = false }
detour = { version = "0.8", features = ["nightly"], default-features = false }
shared = { path = "../shared", default-features = false }
regex = { version = "1.5", default-features = false }
enum-map = { version = "2.3", default-features = false }
u16cstr = { version = "0.3", default-features = false }

[lib]
crate_type = ["cdylib"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
opt-level = 3
