[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = { version = "0.14", default-features = false }
regex = { version = "1.5", features = ["std"], default-features = false }
enum-map = { version = "2.0", default-features = false }

[build-dependencies]
capnpc = "0.14"
cargo-emit = "0.2"
