name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install latest nightly for i686-pc-windows-msvc
      uses: actions-rs/toolchain@v1
      with:
          target: i686-pc-windows-msvc
          toolchain: nightly
          override: true
    
    - name: Install latest nightly for x86_64-pc-windows-msvc
      uses: actions-rs/toolchain@v1
      with:
          target: x86_64-pc-windows-msvc
          toolchain: nightly
          override: true
          
    - name: Build burnt-sushi-blocker
      run: cargo build --manifest-path=burnt-sushi-blocker/Cargo.toml --target i686-pc-windows-msvc
          
    - name: Build burnt-sushi
      run: cargo build --manifest-path=shared/Cargo.toml --target x86_64-pc-windows-msvc
